server:
  port: 8090
documentation:
  swagger:
    services:
      - name: Service1
        url: http://localhost:25010/v2/api-docs
        version: 2.0
      - name: Service2
        url: http://localhost:25002/v2/api-docs
        version: 2.0
